name: "meow_match"
description: Match the pictures


version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  flare_flutter: ^3.0.0
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  shared_preferences: ^2.0.7
  provider: ^6.1.2
  
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/.
    - assets/brain_animation.json
    - assets/brain_animation2.json
    - assets/brain_animation3.json
    - assets/brain_animation4.json
    - assets/Explosion.json

  fonts:
    - family: PressStart2p
      fonts:
        - asset: assets/fonts/PressStart2p_font.ttf


  #   - images/a_dot_ham.jpeg
# 